### ISSUE TITLE
arm64 지원

### ISSUE THREAD

**Issue by issac4892** [aroxu/tidy#1]
라즈베리파이에서도 쓰고 싶어요

**Comment by aroxu** [comment]
소스코드를 받아서 arm64 용으로 빌드하시면 사용하실 수 있습니다. 단 engine만 해당됩니다.
빌드 방법은 Google에 Go언어 arm64 컴파일 이라고 검색하시면 나옵니다.

**Comment by qogusdn1017** [comment]
@issac4892 추후 Engine 사용법 알려줄테니 이슈 닫아주삼
